KERNEL_SIZE: 51
image_size: [120, 120, 3]
primary_samples: 500
backup_samples: 1000
num_epochs: 1001
densification_interval: 300
learning_rate: 0.01
image_file_name: "/media/mldadmin/home/s122mdg39_05/Projects_mrna/data/1213_demo_data_v2/raw1_cropped"
display_interval: 10
gradient_threshold: 0.002
gaussian_threshold: 0.002
display_loss: False
run_name: "debug"
gpu_id: 3